version: '3.9'

services:
  app:
    container_name: budget-tracker
    image: budget-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - budget-tracker
    volumes:
      - .:/app
      - /app/node_modules

networks:
  budget-tracker:
    name: budget-tracker

volumes:
  budget-tracker:
    name: budget-tracker
